version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  search-module:
    image: vinsdocker/containertest:demo
    container_name: search-module
    depends_on:
      - firefox
      - chrome
    environment:
      - MODULE=search-module.xml
      - BROWSER=firefox
      - SELENIUM_HUB=selenium-hub
  order-module:
    image: vinsdocker/containertest:demo
    container_name: order-module
    depends_on:
      - firefox
      - chrome
    environment:
      - MODULE=order-module.xml
      - BROWSER=chrome
      - SELENIUM_HUB=selenium-hub